#!/usr/bin/env bash

composer install --no-interaction --no-dev --optimize-autoloader
npm run prod

# Migrate database
php artisan migrate --force

php artisan config:cache
php artisan route:cache
php artisan view:cache
