# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel:
    build:
      context: ./docker/8.0-prod
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www/html'
    labels:
      caddy: localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - sail
      - caddy
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
  redis:
    image: 'redis:alpine'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  # using caddy network from lab
  caddy:
    external: true
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
