#!/bin/sh
set -e

echo "Deploying application ..."

# Enter maintenance mode
(php artisan down) || true
    # Update codebase
    git fetch origin master
    git reset --hard origin/master

    start-prod

# Exit maintenance mode
php artisan up

echo "Application deployed!"

