#!/usr/bin/env bash

APP_ENV="$1"

if [ "$APP_ENV" = 'prod' ] || [ "$APP_ENV" = 'production' ]; then
    php artisan down

    start-prod

    php artisan up
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
