#!/usr/bin/env bash

# Composer package
composer install --no-interaction --no-dev --optimize-autoloader

php artisan down

# NPM install
npm install
npm run prod

# Migrate database
php artisan migrate --force

# clear caching etc
php artisan config:clear
php artisan route:clear
php artisan view:clear

php artisan up
