#!/usr/bin/env bash


if [ "$APP_ENV" = 'prod' ] || [ "$APP_ENV" = 'production' ]; then
    php artisan down

    start-prod

    php artisan up
fi

#TODO: fix logging output to screen?
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
